# Generated by Django 5.1.1 on 2024-09-24 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InfoCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=150)),
                ('gmail', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_place', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('sessions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoCenter.sessions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationService.users')),
            ],
        ),
    ]
